import {
  Activity,
  BarChart3,
  Shield,
  LineChart,
  Users,
  Trophy,
  Database,
  Settings2,
  FileText,
  MapPin,
  Sparkles,
  Gamepad2,
  Target,
  LayoutDashboard,
  PlusCircle,
} from "lucide-react";

export const navItems = [
  { label: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
  { label: "Match Entry", href: "/add-match", icon: PlusCircle },
  { label: "Team Analysis", href: "/teams", icon: Activity },
  { label: "Player Analysis", href: "/players", icon: Users },
  { label: "Venue Analysis", href: "/venues", icon: MapPin },
  { label: "Toss Analysis", href: "/toss", icon: Target },
  { label: "Opponent Strategy", href: "/opponent-strategy", icon: Shield },
  { label: "Prediction", href: "/prediction", icon: LineChart },
  { label: "Tournament", href: "/tournament", icon: Trophy },
  { label: "Data Manager", href: "/data-manager", icon: Database },
  { label: "Admin", href: "/admin", icon: Settings2 },
  { label: "Reports", href: "/reports", icon: FileText },
];
